name: Build and deploy ASP.Net Core app to Azure Web App - aquacraft-api-priti

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore backend/AquaCraft.API/AquaCraft.API.csproj

      - name: Build
        run: dotnet build backend/AquaCraft.API/AquaCraft.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/AquaCraft.API/AquaCraft.API.csproj --configuration Release --output "${{env.DOTNET_ROOT}}/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_14BDE52D75B14245BDE42ACB41470893 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DEDFBD13CAEC4EEAB7263E47DA8EC3DE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B71EA1A68CE7459B863678F481E80C7F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aquacraft-api-priti'
          slot-name: 'Production'
          package: .
